FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code/
COPY requirements.txt /code/
COPY manage.py /code/
COPY resaleglobal/ ./resaleglobal
RUN ls -alh
RUN pwd
RUN pip install -r requirements.txt

