# Generated by Django 2.2.2 on 2019-08-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0003_categoryresellerrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemattributes',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='AttributeValues',
        ),
    ]
