# Generated by Django 2.2.2 on 2019-09-05 23:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0005_auto_20190905_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemphotos',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        )
    ]
