# Generated by Django 2.2.2 on 2019-09-06 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190725_1257'),
        ('reseller', '0006_auto_20190905_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionResellerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Reseller')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller.Section')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentResellerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller.Department')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Reseller')),
            ],
        ),
    ]
