# Generated by Django 2.2.2 on 2019-09-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190725_1257'),
        ('reseller', '0007_departmentresellerrelationship_sectionresellerrelationship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryresellerrelationship',
            unique_together={('reseller', 'category')},
        ),
    ]
