# Generated by Django 2.2.2 on 2019-06-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='shopify_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
