# Generated by Django 2.2.2 on 2019-06-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconsignorassignment',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='userresllerassignment',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
    ]
