# Generated by Django 2.2.2 on 2019-07-24 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_reseller_shopify_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseller',
            old_name='shopify_key',
            new_name='shopify_access_token',
        ),
        migrations.RemoveField(
            model_name='consignor',
            name='domain',
        ),
    ]
