# Generated by Django 2.2.2 on 2019-06-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190620_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcrelationship',
            old_name='consignor_id',
            new_name='consignor',
        ),
        migrations.RenameField(
            model_name='rcrelationship',
            old_name='reseller_id',
            new_name='reseller',
        ),
        migrations.RenameField(
            model_name='userconsignorassignment',
            old_name='consignor_id',
            new_name='consignor',
        ),
        migrations.RenameField(
            model_name='userconsignorassignment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userresellerassignment',
            old_name='reseller_id',
            new_name='reseller',
        ),
        migrations.RenameField(
            model_name='userresellerassignment',
            old_name='user_id',
            new_name='user',
        ),
    ]
