# Generated by Django 2.2.2 on 2019-07-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190724_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='domain',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
