# Generated by Django 2.0.6 on 2019-05-31 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190530_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastName',
        ),
    ]
